apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-dev
namePrefix: dev-
commonLabels:
  environment: dev
bases:
- ../../base
replicas:
- name: nginx
  count: 4
images:
- name: nginx
  newTag: 1.21-alpine
