apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-prod
namePrefix: prod-
commonLabels:
  environment: prod
bases:
- ../../base
replicas:
- name: nginx
  count: 3
images:
- name: nginx
  newTag: 1.21
resources:
- ingress.yaml
